// Code generated by durable-gen. DO NOT EDIT.

package main

import durable "github.com/danthegoodman1/durable-phases/go"

var ImmediateApprovalWorkflowContract = durable.WorkflowContract[ImmediateInput, ImmediateOutput]{Name: "demo_immediate_approval", Version: 1}

type ImmediateApprovalWorkflowPhase interface{ isImmediateApprovalWorkflowPhase() }

func (BootImmediately) isImmediateApprovalWorkflowPhase()        {}
func (WaitingForApproval) isImmediateApprovalWorkflowPhase()     {}
func (AcknowledgeImmediately) isImmediateApprovalWorkflowPhase() {}

var ImmediateApprovalWorkflowDurableMetadata = struct {
	Name       string
	Version    int
	Input      string
	Output     string
	Common     string
	Phases     []string
	Queries    []string
	Migrations []int
	Signals    []string
	Timers     []string
	Children   []string
}{
	Name:       "demo_immediate_approval",
	Version:    1,
	Input:      "ImmediateInput",
	Output:     "ImmediateOutput",
	Common:     "ImmediateCommon",
	Phases:     []string{"acknowledge_immediately", "boot_immediately", "waiting_for_approval"},
	Queries:    []string{"status"},
	Migrations: []int{},
	Signals:    []string{"approved"},
	Timers:     []string{},
	Children:   []string{},
}
