// Code generated by durable-gen. DO NOT EDIT.

package main

import durable "github.com/danthegoodman1/durable-phases/go"

var GreetingChildWorkflowContract = durable.WorkflowContract[GreetingInput, GreetingChildOutput]{Name: "demo_greeting_child", Version: 1}

type GreetingChildWorkflowPhase interface{ isGreetingChildWorkflowPhase() }

func (ComposeGreeting) isGreetingChildWorkflowPhase() {}

var GreetingChildWorkflowDurableMetadata = struct {
	Name       string
	Version    int
	Input      string
	Output     string
	Common     string
	Phases     []string
	Queries    []string
	Migrations []int
	Signals    []string
	Timers     []string
	Children   []string
}{
	Name:       "demo_greeting_child",
	Version:    1,
	Input:      "GreetingInput",
	Output:     "GreetingChildOutput",
	Common:     "GreetingCommon",
	Phases:     []string{"compose"},
	Queries:    []string{},
	Migrations: []int{},
	Signals:    []string{},
	Timers:     []string{},
	Children:   []string{},
}

var GreetingParentWorkflowContract = durable.WorkflowContract[GreetingInput, GreetingParentOutput]{Name: "demo_greeting_parent", Version: 1}

type GreetingParentWorkflowPhase interface{ isGreetingParentWorkflowPhase() }

func (StartChild) isGreetingParentWorkflowPhase()      {}
func (WaitingForChild) isGreetingParentWorkflowPhase() {}

var GreetingParentWorkflowDurableMetadata = struct {
	Name       string
	Version    int
	Input      string
	Output     string
	Common     string
	Phases     []string
	Queries    []string
	Migrations []int
	Signals    []string
	Timers     []string
	Children   []string
}{
	Name:       "demo_greeting_parent",
	Version:    1,
	Input:      "GreetingInput",
	Output:     "GreetingParentOutput",
	Common:     "GreetingCommon",
	Phases:     []string{"start_child", "waiting_for_child"},
	Queries:    []string{},
	Migrations: []int{},
	Signals:    []string{},
	Timers:     []string{},
	Children:   []string{"greeting_finished"},
}
