package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGeneratorEmitsStableMetadataAndPhaseMarkers(t *testing.T) {
	dir := t.TempDir()
	source := `package workflows

import "context"

type Input struct{}
type Output struct{}
type Common struct{}
type Boot struct{}
type Waiting struct{}
type Done struct{}
type ChildHandle struct{}

//durable:workflow name=sample version=1 input=Input output=Output common=Common
type SampleWorkflow struct{}

//durable:phase name=boot run state=Boot
func (SampleWorkflow) Boot(context.Context, Common, Boot) {}

//durable:phase name=waiting state=Waiting
type WaitingHandlers struct{}

//durable:query name=progress output=Output
func (SampleWorkflow) Progress() {}

//durable:global_signal name=cancel payload=Input
func (SampleWorkflow) Cancel() {}

//durable:timer name=deadline at=DeadlineAt
func (WaitingHandlers) Deadline() {}

//durable:child name=child_done handle=Child
func (WaitingHandlers) ChildDone() {}

//durable:migration from=1
func (SampleWorkflow) FromOne() {}
	`
	if err := os.WriteFile(filepath.Join(dir, "workflow.go"), []byte(source), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := run(dir, "durable_gen.go"); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(dir, "durable_gen.go"))
	if err != nil {
		t.Fatal(err)
	}
	text := string(data)
	for _, want := range []string{
		"Code generated by durable-gen",
		"var SampleWorkflowContract = durable.WorkflowContract[Input, Output]",
		"type SampleWorkflowPhase interface",
		"func (Boot) isSampleWorkflowPhase()",
		"func (Waiting) isSampleWorkflowPhase()",
		`Name: "sample"`,
		`[]string{"progress"}`,
		`[]string{"cancel"}`,
		`[]string{"deadline"}`,
		`[]string{"child_done"}`,
		`[]int{1}`,
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("generated output missing %q:\n%s", want, text)
		}
	}
}

func TestGeneratorRejectsMalformedAnnotations(t *testing.T) {
	dir := t.TempDir()
	source := `package workflows

type Input struct{}
type Output struct{}

//durable:workflow name=sample version=1 input=Input output=Output
type SampleWorkflow struct{}

//durable:timer name=missing_at
func (SampleWorkflow) Broken() {}
`
	if err := os.WriteFile(filepath.Join(dir, "workflow.go"), []byte(source), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := run(dir, "durable_gen.go"); err == nil {
		t.Fatalf("expected malformed timer error")
	}
}

func TestGeneratorRejectsDuplicatePhaseNames(t *testing.T) {
	dir := t.TempDir()
	source := `package workflows

type Input struct{}
type Output struct{}
type State struct{}

//durable:workflow name=sample version=1 input=Input output=Output
type SampleWorkflow struct{}

//durable:phase name=same state=State
type A struct{}

//durable:phase name=same state=State
type B struct{}
`
	if err := os.WriteFile(filepath.Join(dir, "workflow.go"), []byte(source), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := run(dir, "durable_gen.go"); err == nil {
		t.Fatalf("expected duplicate phase error")
	}
}
