// Code generated by durable-gen. DO NOT EDIT.

package main

import durable "github.com/danthegoodman1/durable-phases/go"

var ReminderWorkflowContract = durable.WorkflowContract[ReminderInput, ReminderOutput]{Name: "demo_timer_stay", Version: 1}

type ReminderWorkflowPhase interface{ isReminderWorkflowPhase() }

func (ReminderWaiting) isReminderWorkflowPhase() {}

var ReminderWorkflowDurableMetadata = struct {
	Name       string
	Version    int
	Input      string
	Output     string
	Common     string
	Phases     []string
	Queries    []string
	Migrations []int
	Signals    []string
	Timers     []string
	Children   []string
}{
	Name:       "demo_timer_stay",
	Version:    1,
	Input:      "ReminderInput",
	Output:     "ReminderOutput",
	Common:     "ReminderCommon",
	Phases:     []string{"waiting"},
	Queries:    []string{"progress"},
	Migrations: []int{},
	Signals:    []string{"done"},
	Timers:     []string{"reminder_due"},
	Children:   []string{},
}
