// Code generated by durable-gen. DO NOT EDIT.

package main

import durable "github.com/danthegoodman1/durable-phases/go"

var BatchWorkflowContract = durable.WorkflowContract[BatchInput, BatchOutput]{Name: "demo_checkpoint_loop", Version: 1}

type BatchWorkflowPhase interface{ isBatchWorkflowPhase() }

func (ProcessBatch) isBatchWorkflowPhase() {}

var BatchWorkflowDurableMetadata = struct {
	Name       string
	Version    int
	Input      string
	Output     string
	Common     string
	Phases     []string
	Queries    []string
	Migrations []int
	Signals    []string
	Timers     []string
	Children   []string
}{
	Name:       "demo_checkpoint_loop",
	Version:    1,
	Input:      "BatchInput",
	Output:     "BatchOutput",
	Common:     "struct{}",
	Phases:     []string{"process_batch"},
	Queries:    []string{},
	Migrations: []int{},
	Signals:    []string{},
	Timers:     []string{},
	Children:   []string{},
}
