// Code generated by durable-gen. DO NOT EDIT.

package main

import durable "github.com/danthegoodman1/durable-phases/go"

var MigratingOrderV1Contract = durable.WorkflowContract[OrderInput, OrderOutput]{Name: "demo_migrating_order", Version: 1}

type MigratingOrderV1Phase interface{ isMigratingOrderV1Phase() }

func (WaitingV1) isMigratingOrderV1Phase() {}

var MigratingOrderV1DurableMetadata = struct {
	Name       string
	Version    int
	Input      string
	Output     string
	Common     string
	Phases     []string
	Queries    []string
	Migrations []int
	Signals    []string
	Timers     []string
	Children   []string
}{
	Name:       "demo_migrating_order",
	Version:    1,
	Input:      "OrderInput",
	Output:     "OrderOutput",
	Common:     "OrderCommonV1",
	Phases:     []string{"waiting"},
	Queries:    []string{},
	Migrations: []int{},
	Signals:    []string{"finish"},
	Timers:     []string{},
	Children:   []string{},
}

var MigratingOrderV2Contract = durable.WorkflowContract[OrderInput, OrderOutput]{Name: "demo_migrating_order", Version: 2}

type MigratingOrderV2Phase interface{ isMigratingOrderV2Phase() }

func (WaitingForFinishV2) isMigratingOrderV2Phase() {}

var MigratingOrderV2DurableMetadata = struct {
	Name       string
	Version    int
	Input      string
	Output     string
	Common     string
	Phases     []string
	Queries    []string
	Migrations []int
	Signals    []string
	Timers     []string
	Children   []string
}{
	Name:       "demo_migrating_order",
	Version:    2,
	Input:      "OrderInput",
	Output:     "OrderOutput",
	Common:     "OrderCommonV2",
	Phases:     []string{"waiting_for_finish"},
	Queries:    []string{},
	Migrations: []int{1},
	Signals:    []string{"finish"},
	Timers:     []string{},
	Children:   []string{},
}
